### ISSUE TITLE
Please add a sample input and output

### ISSUE THREAD

**Issue by thesteve0** [regrenos/teamgenerator#4]
Please put in a hand crafted file for what you expect as input and what you expect as output. Please only have like 4 students or something in it so it is easy to track in our heads

**Comment by stevekuznetsov** [comment]
I've added some sample input files in .XLS, .XLSX, and .csv (will add openoffice formats soon) in #1 - what output do you want to see? Currently the code is running this through a `LateX` process and outputting PDFs - I guess we can continue having the backend do that and give users access to PDFs as outputs online, does that sound fine? I'm not sure if some pretty bootstrapped tables would be better to present to users & allow for download.

**Comment by thesteve0** [comment]
This is your app - what do you want?

**Comment by stevekuznetsov** [comment]
@thesteve0 What did I want? Answers, not questions! :)

**Comment by thesteve0** [comment]
Yes young grasshopper and my answer is a question.
Slacker - it's your app - you define the output format! ;)

**Comment by stevekuznetsov** [comment]
Sample output is coming (#8) - I'm trying to use Apache FOP, with a workflow that is like this:

Java objects -> XML using JAXB -> XSL-FO -> PDF using Apache FOP.

Currently I'm at a stage where I create valid XSL-FO documents as far as I can tell but my PDF output is corrupted. I wish this package had better documentation! @thesteve0

**Comment by stevekuznetsov** [comment]
@thesteve0 Finally got it working - here's an [example output for a group](https://github.com/stevekuznetsov/teamgenerator/blob/refactor-pdf/examples/output/group.pdf)

**Comment by thesteve0** [comment]
PDF box is what I would use for PDF output but more power to you!

**Comment by stevekuznetsov** [comment]
I looked into it but FOP seemed better? Not sure

**Comment by thesteve0** [comment]
Ok well if it worked for you, who am I to argue

**Comment by stevekuznetsov** [comment]
@thesteve0 Added [sample output](https://github.com/stevekuznetsov/teamgenerator/blob/refactor-pdf/examples/output/sectiongrouping.pdf) for a class!
